added tab bar for settings_component.dart
shuffle-app/shuffle_componentskit pull request #116
Opened 2023-09-08 15:42 UTC by donik1998

2023-09-08 16:34 UTC, romancores requested changes

2023-09-08 16:34 UTC, romancores commented on lib/presentation/components/profile/settings_component/settings_component.dart
> +  final ValueChanged<String>? onTabSwotched;
айай, исправить название

2023-09-12 14:41 UTC, romancores approved these changes

2023-09-12 15:44 UTC, naveenpardeep approved these changes

2023-09-12 16:47 UTC, merged