Sfk 238
shuffle-app/shuffle_componentskit pull request #327
Opened 2024-06-20 11:38 UTC by ParaDox-PDT

2024-06-21 16:32 UTC, romancores requested changes

2024-06-21 16:32 UTC, romancores commented on lib/presentation/components/company_presentation/company_presentation_component.dart
> +              children: List.generate(
лучше используй listView.separated и ставь padding: .symmetric(horizontal: EdgeInsetsFoundation.horizontal8)

2024-06-21 16:32 UTC, romancores commented on lib/presentation/components/company_presentation/company_presentation_component.dart
> +                    child: ListView(
то же самое - listView.builder или listView.separated

2024-06-21 16:32 UTC, romancores commented on lib/presentation/components/company_presentation/company_presentation_component.dart
> +                    BaseUiKitButtonData(text: S.current.Next, onPressed: () {}),
сюда надо прокидывать колбек на onNext из родителя

2024-06-24 09:36 UTC, ParaDox-PDT commented on lib/presentation/components/company_presentation/company_presentation_component.dart
> +              children: List.generate(
fixed

2024-06-24 09:36 UTC, ParaDox-PDT commented on lib/presentation/components/company_presentation/company_presentation_component.dart
> +                    child: ListView(
fixed

2024-06-24 09:37 UTC, ParaDox-PDT commented on lib/presentation/components/company_presentation/company_presentation_component.dart
> +                    BaseUiKitButtonData(text: S.current.Next, onPressed: () {}),
fixed

2024-06-24 20:47 UTC, romancores approved these changes

2024-06-24 21:00 UTC, merged