Sfk 259
shuffle-app/shuffle_componentskit pull request #330
Opened 2024-06-21 14:27 UTC by ParaDox-PDT

2024-06-24 20:47 UTC, romancores requested changes

2024-06-24 20:47 UTC, romancores commented on lib/presentation/components/invite/invite_component.dart
> +    required Null Function(List<UiInvitePersonModel> persons)
зачем эту функцию добавил? вообще убери изменения инвайт компонента, ты же над ним работал

2024-06-24 20:47 UTC, romancores commented on lib/presentation/utils/component_builder.dart
> +// import 'package:flutter_mobx/flutter_mobx.dart';
также верни обратно. зачем изменял?

2024-06-24 20:47 UTC, romancores commented on lib/presentation/components/property_management/categories_create_component.dart
> +      required this.propertySearchOptions,
очень большой список переменных влиящих на перебилживание виджета, может что-то можно сделать в логике внутри компонента если виджет сделать стейтфул? или создать контроллер в котором будут все эти переменные? надо подумать, не нравится столько параметров, можно созвониться подумать вместе как упростит

2024-06-27 16:37 UTC, ParaDox-PDT commented on lib/presentation/components/invite/invite_component.dart
> +    required Null Function(List<UiInvitePersonModel> persons)
fixed

2024-06-27 16:38 UTC, ParaDox-PDT commented on lib/presentation/utils/component_builder.dart
> +// import 'package:flutter_mobx/flutter_mobx.dart';
fixed

2024-06-28 12:50 UTC, romancores approved these changes

2024-06-28 12:50 UTC, merged